### ISSUE TITLE
无法加载插件，httpcat寻找不到

### ISSUE THREAD

**Issue by ABKQPO** [zhulinyv/nonebot_plugin_ping#6]
`04-20 21:05:54 [ERROR] nonebot | Failed to import "nonebot_plugin_ping"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_ping\__init__.py", line 14, in <module>
    from .httpcat import httpcat_msgs
ModuleNotFoundError: No module named 'nonebot_plugin_ping.httpcat'`

**Comment by zhulinyv** [comment]
不好意思传错了
