### ISSUE TITLE
pingIP时出错

### ISSUE THREAD

**Issue by ABKQPO** [zhulinyv/nonebot_plugin_ping#7]
04-21 19:31:23 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_ping) failed.
Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 33, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\streams\tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 31, in read
    with anyio.fail_after(timeout):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\http11.py", line 105, in handle_async_request
    raise exc
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\http11.py", line 84, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\http11.py", line 148, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_event
    data = await self._network_stream.read(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\backends\asyncio.py", line 30, in read
    with map_exceptions(exc_map):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_ping\__init__.py", line 24, in _
    message = await api_ping(api)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_ping\__init__.py", line 35, in api_ping
    res = (await client.get(api)).json()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

**Comment by zhulinyv** [comment]
接口炸了（
已更换
